In [76]:
import pandas as pd
import numpy as np

In [77]:
data = pd.read_csv(r'C:/Users/Avik/Desktop/breast-cancer-wisconsin.csv')
data.shape
data.iloc[22] #ew, missing data

1000025    1057013
5                8
1                4
1.1              5
1.2              1
2                2
1.3              ?
3                7
1.4              3
1.5              1
2.1              4
Name: 22, dtype: object

In [78]:
data.replace('?', np.NaN, inplace=True) #lets just drop the ~10 rows with missing data
data.dropna(inplace=True)
data.shape

(682, 11)

In [79]:
data = data.values
data

array([[1002945, 5, 4, ..., 2, 1, 2],
       [1015425, 3, 1, ..., 1, 1, 2],
       [1016277, 6, 8, ..., 7, 1, 2],
       ..., 
       [888820, 5, 10, ..., 10, 2, 4],
       [897471, 4, 8, ..., 6, 1, 4],
       [897471, 4, 8, ..., 4, 1, 4]], dtype=object)

In [80]:
data.shape

(682, 11)

In [81]:
data[:,10] = (data[:, 10] / 2) - 1

In [82]:
data[np.random.choice(data.shape[0], 10),:]

array([[785615, 8, 6, 7, 3, 3, '10', 3, 4, 2, 1.0],
       [1293966, 4, 1, 1, 1, 2, '1', 1, 1, 1, 0.0],
       [809912, 10, 3, 3, 1, 2, '10', 7, 6, 1, 1.0],
       [1183983, 9, 5, 5, 4, 4, '5', 4, 3, 3, 1.0],
       [1321942, 5, 1, 1, 1, 2, '1', 3, 1, 1, 0.0],
       [1173235, 3, 3, 2, 1, 2, '3', 3, 1, 1, 0.0],
       [1152331, 4, 1, 1, 1, 2, '1', 3, 1, 1, 0.0],
       [1152331, 4, 1, 1, 1, 2, '1', 3, 1, 1, 0.0],
       [1238410, 2, 3, 1, 1, 3, '1', 1, 1, 1, 0.0],
       [1167471, 4, 1, 2, 1, 2, '1', 3, 1, 1, 0.0]], dtype=object)

In [83]:
import sklearn
from sklearn.ensemble import RandomForestClassifier

In [108]:
clf = RandomForestClassifier(min_samples_split=4)
X = data[:-10,1:9].astype(int)
y = (data[:-10,10]).astype(int)
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=4,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [113]:
X_test = X[-10:, :]
y_test = y[-10:]
print(clf.predict(X_test))
print(y_test)

[0 1 1 0 0 0 0 0 0 0]
[0 1 1 0 0 0 0 0 0 0]
